apiVersion: apps/v1
kind: Deployment
metadata:
  name: erduo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erduo
  template:
    metadata:
      labels:
        app: erduo
    spec:
      containers:
      - image: okteto.dev/erduo:latest
        name: erduo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "56543a30-87c8-4b26-a201-d26eb43222c9"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "56543a30-87c8-4b26-a201-d26eb43222c9"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
